// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bubble/internal/biz"
	"bubble/internal/conf"
	"bubble/internal/data"
	"bubble/internal/server"
	"bubble/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

/*
wire的使⽤用：
1. ⼀一般⼤大型项⽬目会⽤用到。
2. 编写代码时注意使⽤用依赖注⼊入，把⽤用到的依赖项使⽤用参数传⼊入，⽽而不不是⾃自⼰己直接写死。
3. 使⽤用wire把构造函数连接起来，编写⼀一个注⼊入器器。
4. 命令⾏行行⼯工具wire⽣生成Go代码到wire_gen.go⽂文件。
5. 调⽤用 wire_gen.go 中⽣生成的函数。
注意的地⽅方：
1. wire.go 最上⾯面要加 //go:build wireinject
2. wire.go 需要和最终产出对象在同⼀一个包内。在哪⾥里里⽤用就在哪⾥里里创建wire.go⽂文件
*/
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData, logger)
	todoUsecase := biz.NewTodoUsecase(todoRepo, logger)
	todoService := service.NewTodoService(todoUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService, logger)
	httpServer := server.NewHTTPServer(confServer, todoService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
